# Generated by Django 5.0 on 2026-05-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kaucja'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_period',
            field=models.CharField(choices=[('day', 'dzień'), ('week', 'tydzień'), ('month', 'miesiąc')], default='day', max_length=10, verbose_name='Jednostka najmu'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stawka najmu (za dzień)'),
        ),
    ]
