# Generated by Django 5.0 on 2026-05-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_payment_status_order_payu_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderequipment',
            name='deposit_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderequipment',
            name='rental_rate_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
