# Generated by Django 5.0 on 2026-05-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderequipment_deposit_at_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
